apiVersion: v1
kind: Pod
metadata:
  name: rabbit-sample-consumer
spec:
  containers:
  - name: rabbit-sample-consumer
    image: rabbit-sample-consumer
    imagePullPolicy: Never
    ports:
    - containerPort: 5672
    - containerPort: 15672
    envFrom:  
    - secretRef:
        name: zone-sensitive-rabbit-sec
    env:
    - name: SAMPLE_QUEUE
      value: queue-jobs
    - name: SAMPLE_EXCHANGE
      value: app
    - name: SAMPLE_RABBIT_HOST
      value: rabbit-svc.broker-zone.svc.cluster.local
    - name: SAMPLE_RABBIT_PORT
      value: "5672"
    - name: SAMPLE_VHOST
      value: zone-sensitive

