# permissions for end users to edit hazyzones.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: hazyzone-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: hazy-rabbit-operator
    app.kubernetes.io/part-of: hazy-rabbit-operator
    app.kubernetes.io/managed-by: kustomize
  name: hazyzone-editor-role
rules:
- apiGroups:
  - hazy.hazy.com
  resources:
  - hazyzones
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hazy.hazy.com
  resources:
  - hazyzones/status
  verbs:
  - get
