---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - hazy.hazy.com
  resources:
  - hazyzones
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hazy.hazy.com
  resources:
  - hazyzones/finalizers
  verbs:
  - update
- apiGroups:
  - hazy.hazy.com
  resources:
  - hazyzones/status
  verbs:
  - get
  - patch
  - update
